package com.company;

import java.util.Scanner; // Scanner util imported for Scanner object to take user input and put it into values/output
import java.lang.Math; // Math object to generate random numbers

public class Main {

    public static void main(String[] args) {

        // print the ASCII numbers from the AsciiChars class
        AsciiChars.printNumbers();
        AsciiChars.printLowerCase();
        AsciiChars.printUpperCase();

        Scanner scannerObjMain = new Scanner(System.in); // Scanner object for user input in main
        System.out.print("Please enter your name: "); // type a name string and hit enter
        String userName = scannerObjMain.next(); // takes the name String and makes it the value of the "name" variable
        System.out.println("Do you wish to continue to the interactive portion, " + userName + "? (y/yes || n/no)");
        String responseYesNo = scannerObjMain.next(); // takes user response and makes it a String value

        /* "After the name prompt, ask the user if they wish to continue to the interactive portion.
        If they enter 'yes' or 'y', continue. Otherwise, quit the program with a message to please return later
        to complete the survey." */

        if (responseYesNo.equals("yes") || responseYesNo.equals("y")) {
            questionnaire();
            System.out.println("Would you like to generate another set of numbers?");
            Scanner scannerObj2 = new Scanner(System.in); // Scanner object for user input in main
            String responseAnotherSet = scannerObj2.nextLine();
            if (responseAnotherSet.equals("yes") || responseAnotherSet.equals("y")) {
                questionnaire();
            } // otherwise, it exits the program, so no else needed here.X
        }
    }

    public static void questionnaire() {
        Scanner scannerObjQR = new Scanner(System.in); // Scanner object for user input in questions
        System.out.println("Do you have a red car? (y/n)");
        String responseCarRed = scannerObjQR.next();

        System.out.println("What's the name of your favorite pet?");
        String responsePetName = scannerObjQR.next();

        System.out.println("What's the age of your favorite pet?");
        int responsePetAge = scannerObjQR.nextInt();

        System.out.println("What's your lucky number?");
        int responseLuckyNum = scannerObjQR.nextInt();

        System.out.println("What's the two-digit model year of your car?");
        int responseCarYear = scannerObjQR.nextInt();
        scannerObjQR.nextLine();

        System.out.println("What's the name of your favorite actor/actress?");
        String responseFaveActor = scannerObjQR.nextLine();


        System.out.println("Enter a random number between 1 and 50.");
        int responseRandNum = scannerObjQR.nextInt();
        scannerObjQR.nextLine(); //trailing newLine fix
        System.out.println("\n");

        /* Generating numbers (section) for the lottery!
        * // Generating three random integers for lottery randomness between 1 and 65 */
        int numRandom1 = (int) (65 * Math.random() + 1);
        int numRandom2 = (int) (65 * Math.random() + 1);
        int numRandom3 = (int) (65 * Math.random() + 1);

        // Generating magic ball number (less than the max magic number of 75)
        int magicBallNumber = responseLuckyNum * numRandom1; // magic number generated by multiplying the req variables
        if (magicBallNumber > 75) { // conditional that checks if the magic num is over 75
            while (magicBallNumber > 75) { /* while loop that subtracts via 75 if it's over until the magic number is
                at or under 75 */
                magicBallNumber -= 75; // refer comment above
            }
        }

        /* non-magic numbers and how they're generated */

        // Use car year + lucky number
        int nonMagic1 = responseCarYear + responseLuckyNum;
        // Use the value 42
        int nonMagic2 = 42;
        // Use the age of their favorite pet + their car model year
        int nonMagic3 = responsePetAge + responseCarYear;
        // Convert the first letter of their favorite actor/'tress to an integer and use that value
        int nonMagic4 = responseFaveActor.charAt(0); // getting/"casting" first char(acter) value of fave actor to int
        // Convert the last letter of their favorite actor/'tress to an integer and use that value
        int nonMagic5 = responseFaveActor.charAt(responseFaveActor.length() - 1); // "casting" the last char into an int

        /* Printing the lottery numbers */
        System.out.println("Lottery numbers: " + nonMagic1 + ", " + nonMagic2 + ", " + nonMagic3 + ", " + nonMagic4 +
                ", " + nonMagic5 + " " + " Magic ball: " + magicBallNumber);

        /* After the numbers have been printed, ask the user if they would like to answer questions
         * to generate another set of numbers.  If so, repeat the entire process.  If not, print a thank you message
         * and exit.
         */

    }
}